server.error.include-stacktrace: always
metadata.file: classpath:AzureMetadata.xml
private.key: azure/dev1.key
public.certificate: azure/dev1.crt
registration.id: azure

server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456789
