spring:
  security:
    saml2:
      relyingparty:
        registration:
          azure:
            entity-id: batoac.com
            signing:
              credentials:
                - private-key-location: classpath:azure/dev1.key
                  certificate-location: classpath:azure/dev1.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"
            assertingparty:
              metadata-uri: "classpath:AzureMetadata.xml"

server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456789
