server.error.include-stacktrace: always
metadata.file: classpath:OktaMetadata.xml
private.key: local.key
public.certificate: local.crt
registration.id: okta
entity.id: noValue

server:
  forward-headers-strategy: native
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456789

logging:
  level:
    root: DEBUG

