server.error.include-stacktrace: always
metadata.file: classpath:AzureMetadata.xml
private.key: azure2/private_key.pem
public.certificate: azure2/public_key.crt
registration.id: azure
entity.id: batoac.com



server:
  forward-headers-strategy: native
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456789


logging:
  level:
    root: DEBUG