server.error.include-stacktrace: always
metadata.file: classpath:OktaMetadata.xml
private.key: local.key
public.certificate: local.crt
registration.id: okta

server:
  servlet:
    session:
      timeout: 5m



